#include finetuning_squad.yml
epochs: 1


model: distilbert-base-uncased
fc_size: 128

env:
  fp16: false
  n_gpu: 1

loader:
  batch_size: 16
  num_workers: 0
  pin_memory: false
  drop_last: true

optim:
  name: adamw
  lr: 1e-3

scheduler:
  name: cycle
  n_iter: 8_144
  decay: lin, cos