env:
    distributed: true
    fp16: true
    n_gpu: 4
    seed: 42

dataset:
    name: dataset
    path: dataset.lmdb
    resolution: 256

loader:
    batch_size: 32
    drop_last: true

optim:
    name: adamw
    lr: 5e-5
    b1: 0.9
    b2: 0.999
    devay: 5e-6

scheduler:
   name: cycle
   n_iter: 1_000
   warmup: 100
   plateau: 50
   decay: lin, cos