n_iter: 100
seed: 42
size: 224

style: https://storage.googleapis.com/download.tensorflow.org/example_images/Vassily_Kandinsky%2C_1913_-_Composition_7.jpg
style_layers: [0, 5, 10, 19, 28]
style_weights: [1.0, 0.8, 0.5, 0.3, 0.1]
style_weight: 1e6

content: https://storage.googleapis.com/download.tensorflow.org/example_images/YellowLabradorLooking_new.jpg
content_layers: 21
content_weights: 1.0
content_weight: 1.0

env:
  n_gpu: 1

optim:
  name: adamw
  lr: 2e-2