epochs: 20
seed: 42

z_dim: 128
grad_penalty: 5.0

env:
  fp16: true
  n_gpu: 1

dataset:
  name: mnist
  root: /tmp/mnist

loader:
  batch_size: 256
  num_workers: 10
  pin_memory: true
  drop_last: true

optim:
  name: adamw
  lr: 1e-3

scheduler:
  name: cycle
  n_iter: 4_680
  decay: lin, cos